# Generated by Django 5.2.3 on 2025-08-09 03:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_add_frozenState'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_auth',
            field=models.CharField(blank=True, choices=[('enable', 'Enable'), ('disable', 'Disable')], default='Enable', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_pic'),
        ),
    ]
